Portfolio: Finish mobile version
rabayarabu/Portfolio-setup-and-mobile-first pull request #2
Opened 2023-03-24 18:52 UTC by rabayarabu

Portfolio: Finish mobile version

1. Include images
2. Edit index.html file
3. Edit style.css file

2023-03-24 19:55 UTC, Shisui6 requested changes
Hi @rabayarabu, 

# Requires Changes 🍀
You have done an excellent job!👏👏
Your design is spot on 🖼️, and your code follows best practices. There are just a few more things to work on🪲

## Highlights
- Excellent design ✅
- Great use of grid and flexbox ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

You can also consider the following:

N/A

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 19:55 UTC, Shisui6 commented on index.html
> +                <h1>My Recent Works</h1>
Kindly update this element to use another `<hx>` element apart from `<h1>`🙏. This is for semantic reasons, as a good webpage is typically supposed to have one `<h1>` tag which represents the main title

2023-03-24 19:55 UTC, Shisui6 commented on index.html
> +                    <button type="button">See project</button>
Kindly update **all** buttons on your page to have button interaction styling when hovered and pressed. You can use the `:hover` and `:active` pseudo selectors to achieve this. When doing so, please stick to the figma design guidelines for button styling👍:
<img width="447" alt="image" src="https://user-images.githubusercontent.com/37116322/227625333-8e41a397-0644-476c-917a-a378863d2b1b.png">

2023-03-24 19:55 UTC, Shisui6 commented on index.html
> +            <h1>About me</h1>
Kindly update this element to use another `<hx>` element apart from `<h1>`🙏. This is for semantic reasons, as a good webpage is typically supposed to have one `<h1>` tag which represents the main title

2023-03-24 19:55 UTC, Shisui6 commented on index.html
>          <!-- headline section -->
Kindly remove the below line in your readme file:
<img width="620" alt="image" src="https://user-images.githubusercontent.com/37116322/227625940-f328b4d9-f1a8-4ba9-8407-a51b1a0cd6f9.png">
 This note is a part of the guideline template and should not be part of your final readme

2023-03-24 21:02 UTC, vickymarz requested changes
Hi @rabayarabu, 

Great work on making the changes requested by a previous reviewer 👏 🔥 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## Top highlight 🎯

- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 21:02 UTC, victorokoroji commented on index.html
> +                    <button type="button">See project</button>
- [ ] As suggested by the previous reviewer, kindly update all buttons on your page to have button interaction styling when hovered and pressed. You can use the` :hover `and `:active` pseudo selectors to achieve this. When doing so, please stick to the figma design guidelines for button styling👍:

![image](https://user-images.githubusercontent.com/63473584/227639943-56206a43-9a6c-4420-9610-5dcd0730ff31.png)

2023-03-25 12:15 UTC, Strangeal requested changes
Hi @rabayarabu, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![Alt Text](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

 ## Required Changes ♻️
- [ ] As suggested by the previous reviewer, kindly update all buttons on your page to have button interaction styling when hovered and pressed. You can use the `:hover `and `:active `pseudo selectors to achieve this. When doing so, please stick to the Figma design guidelines for button styling👍:

<img width="594" alt="Screenshot 2023-03-25 at 05 13 51" src="https://user-images.githubusercontent.com/107192076/227716760-db6ce182-f05c-416a-bf56-4e0664466fa4.png">

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-25 13:19 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:

Hi @rabayarabu 
Your project is complete! Great job for making the requested changes 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- great design
- No linter errors

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-25 13:23 UTC, merged